project:
  type: book
  output-dir: docs

book:
  title: "**BIOL4062/5062 Analysis of Biological Data: Assignment Guide**"
  author: "Reid Steele"
  date: "2024-11-04"
  search: true
  repo-url: "https://github.com/Future-of-Marine-Ecosystems/BIOL4062-5062-Assignment-Guide/"
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "**Assignment 1**"
      chapters:
        - a1a.qmd
        - a1b.qmd
        - a1c.qmd
        - a1d.qmd
        - a1e.qmd
    - guidelines.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

