project:
  type: book
  output-dir: docs

book:
  title: "**Assignment 1 Guide**"
  subtitle: "BIOL4062/5062: Analysis of Biological Data"
  author: "Reid Steele (Based on work by Ana Eguiguren)"
  date: "2025-09-19"
  cover-image: FOME_Primary_BlueGradient.png
  search: true
  navbar:
    logo: FOME_Small.png
  repo-url: https://github.com/Future-of-Marine-Ecosystems/BIOL4062-5062-Assignment-Guide/
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    - guidelines.qmd
    - part: "**R Refresher**"
      chapters:
        - refresher_1.qmd
        - refresher_2.qmd
        - refresher_3.qmd
        - refresher_4.qmd
        - refresher_5.qmd
        - refresher_6.qmd
        - refresher_7.qmd
        - refresher_8.qmd
        - refresher_9.qmd
    - part: "**Assignment 1**"
      chapters:
        - a1a.qmd
        - a1b.qmd
        - a1c.qmd
        - a1d.qmd
        - a1e.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  freeze: auto

