project:
  type: book
  output-dir: docs

book:
  title: "**Assignment 1 Guide**"
  subtitle: "BIOL4062/5062: Analysis of Biological Data"
  author: "Reid Steele (Based on work by Ana Eguiguren)"
  date: "2024-11-04"
  cover-image: FOME_Primary_BlueGradient.png
  search: true
  repo-url: https://github.com/Future-of-Marine-Ecosystems/BIOL4062-5062-Assignment-Guide/
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    - guidelines.qmd
    - part: "**Assignment 1**"
      chapters:
        - a1a.qmd
        - a1b.qmd
        - a1c.qmd
        - a1d.qmd
        - a1e.qmd

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

editor: visual

