project:
  type: book

book:
  title: "Analysis of Biological Data: Assignment Guide"
  author: "Reid Steele"
  date: "2024-11-04"
  chapters:
    - index.qmd
    - a1a.qmd
    - a1b.qmd
    - a1c.qmd
    - a1d.qmd
    - a1e.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

