# **Assignment Guidelines** {.unnumbered}

This section provide general advice on how to approach your assignments, and also describes how to format them:

## General Advice

**1. Read the grading rubric carefully!**

-   It is designed to be as objective as possible. There is little latitude for part marks if you are missing things that are listed.

**2. You don't need to describe the statistical theory (unless it's relevant to your answers)**

-   All you have to do is answer the questions in the assignment. Anything you write outside of that is just eating up your page limit.

**3. However, biological interpretations are important: put them together at the end**

-   Your interpretations are more likely to make sense and be easier to mark if you put them at the end, including all of your results together in them, rather than inserting them throughout piecemeal.

-   **Also, make sure your biological interpretations are consistent with your data/results! They don't have to be correct, but they do have to match your data.**

**4. Make sure your figures are readable**

-   We can't tell if your interpretation of your figures is correct if we can't interpret your figures.

-   All text on figures should be legible.

-   If you use color, make sure that the colors you use are clearly distinguishable (and consider colour-blind safe palettes)

**5. You're not alone!**

-   If you have questions, come to the drop-in sessions, read the Brightspace discussion boards, or email the TA to ask questions or set up a meeting if those options don't work for you.

-   Do the first two (drop-in sessions, Brightspace discussion boards) even if you don't have questions: you may find the answer to questions you didn't know you had.

-   You're also welcome to ask questions after an assignment has been graded, if you want to know why you were graded the way you were, or if you have questions about the comments provided or what you may have done wrong.

**6. Ask if you need an extension**

-   We're pretty reasonable.

## Submission Formatting

Please format your submission following these guidelines: it will make both our lives easier.

**1. Hand in your assignment in 3 parts:**

a\)  Your assignment text

-   All assignment 1s have a 2 page limit. Put all your text first, with figures and tables together separately at the end. It is easier for me to tell how many pages you wrote this way. You're not going to lose marks if you're slightly over (this is not a writing class).
-   Should be a word doc or PDF file so it can be opened in BrightSpace. It doesn't matter whether it's produced through word, markdown, etc, as long as it's in one of those two formats.

b\) Your script, submitted as a .txt file

-   Submitting as a .txt file allows us to open the script in BrightSpace rather than having to download it if it's a .R file. Please don't paste your script in your assignment document.

c\) The data you read into your script

-   This is just to make it easy to run your script if there is a mistake.

***Note: If you do your assignments in markdown, you can combine a) and b)***

**2. Don't put your name on your assignments, in your scripts, or in any of your file names**

-   The BrightSpace system of using Banner ID numbers is anonymous so your assignments are marked blind by the TA. That doesn't work if you write your name.

-   Delete your file paths in your script for submission if they have your name in them.

-   **You do need to put your B0 number, data code number, and whether you're a graduate student or an undergraduate student.**

**3. Follow the assignment guides on this site**

-   You don't have to follow this guide to get full marks on the assignments (as always, there are many correct answers when it comes to statistics and coding). That said, it's easier to follow what you're doing if you're doing the same thing as everyone else.

-   It's OK to do your own thing, but if you make a mistake, its going to be much harder to help you out, and it's going to take significantly more effort to mark.
